Added repp removal

diff --git a/.github/workflows/remove_st_after_pr.yml b/.github/workflows/remove_st_after_pr.yml
--- a/.github/workflows/remove_st_after_pr.yml
+++ b/.github/workflows/remove_st_after_pr.yml
@@ -71,6 +71,7 @@ jobs:
           cd "$REPO"/"$PR_REF"
           export KUBECONFIG=./kubeconfig
           helm delete reg-admin-"$PR_REF" -n reg-admin-staging
+          helm delete repp-"$PR_REF" -n epp
           rm kubeconfig
           echo "server obs.tld.ee
           zone pilv.tld.ee
@@ -78,9 +79,20 @@ jobs:
           send
           " | nsupdate -k ~/Kgh-runner.infra.tld.ee.+165+27011.key
           if [ "$?" -eq "0" ]; then
-              echo "CNAME update success"
+              echo "admin CNAME update success"
           else
-              echo "CNAME update failed"
+              echo "admin CNAME update failed"
+          fi
+          EOSSH
+          echo "server obs.tld.ee
+          zone pilv.tld.ee
+          update delete repp-"$PR_REF".pilv.tld.ee.
+          send
+          " | nsupdate -k ~/Kgh-runner.infra.tld.ee.+165+27011.key
+          if [ "$?" -eq "0" ]; then
+              echo "repp CNAME update success"
+          else
+              echo "repp CNAME update failed"
           fi
           EOSSH
 
@@ -95,7 +107,7 @@ jobs:
             |:-----------|:-------------------------------------------:|
             | **Admin**  | ~~https://reg-admin-'$PR_REF'.pilv.tld.ee~~ |
             | **API**    | ~~https://reg-api-'$PR_REF'.pilv.tld.ee~~   |
-            | **REPP**   | ~~https://reg-repp-'$PR_REF'.pilv.tld.ee~~  |
+            | **REPP**   | ~~https://repp-'$PR_REF'.pilv.tld.ee~~      |
             | **EPP**    | ~~https://reg-epp-'$PR_REF'.pilv.tld.ee~~   |
             "
             }' $NOTIFICATION_URL
